# Generated by Django 6.0.4 on 2026-04-23 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المهمة/المنطقة')),
                ('latitude', models.FloatField(verbose_name='خط العرض (Lat)')),
                ('longitude', models.FloatField(verbose_name='خط الطول (Lon)')),
                ('radius_meters', models.IntegerField(default=100, verbose_name='نطاق السماح (بالمتير)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecureMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_payload', models.BinaryField(verbose_name='النص المشفر')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('is_destroyed', models.BooleanField(default=False, verbose_name='مدمرة ذاتياً')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='الفرد')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='القائد')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noor.securityzone', verbose_name='المنطقة الأمنية')),
            ],
            options={
                'verbose_name': 'رسالة مؤمنة',
                'verbose_name_plural': 'الرسائل المؤمنة',
            },
        ),
    ]
